### ISSUE TITLE
Dashboard_element

### ISSUE THREAD

**Issue by Pugma** [traP-jp/yaranai_frontend#6]
ダッシュボードでの構成要素を配置する
デザインは別issueで

**Comment by E2-genomu** [comment]
assignされておいた
さっき(23:00手前)に投げたプルリクで問題なければ、
・サジェスチョン
・未設定のタスク
は再修正いるけどタスクのハードルごとのほうは実装したつもりです

**Comment by E2-genomu** [comment]
Doneにしとく？
